spring:
  datasource:
    username: root
    password: zhangsiwen
    url: jdbc:mysql://localhost:3306/flighttest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  messages:
    basename: internationalization.login

mybatis:
  mapper-locations: classpath:mybatis/mapper/**.xml
  type-aliases-package: jmu.vo
  config-location: classpath:mybatis-config.xml

#showSql
logging:
  level:
    jmu.mapper: debug